# -*- coding: utf-8 -*-
# База данных локаций Albion Online
ALBION_LOCATIONS = [
    ("Morgana's Rest", "⛺ Morgana's Rest"),
    ("Arthur's Rest", "⛺ Arthur's Rest"),
    ("Merlyn's Rest", "⛺ Merlyn's Rest"),
    
    # Tier V Swamps (🐉)
    ("Drownfield Course", "V 🐉 Drownfield Course"),
    ("Drownfield Fen", "V 🐉 Drownfield Fen"),
    ("Drownfield Mire", "V 🐉 Drownfield Mire"),
    ("Longfen Marsh", "V 🐉 Longfen Marsh"),
    ("Runnelvein Slough", "V 🐉 Runnelvein Slough"),
    ("Scuttlesink Pools", "V 🐉 Scuttlesink Pools"),
    ("Skullmarsh Lower", "V 🐉 Skullmarsh Lower"),
    ("Wetgrave Bog", "V 🐉 Wetgrave Bog"),
    ("Widemoor Delta", "V 🐉 Widemoor Delta"),
    ("Widemoor Estuary", "V 🐉 Widemoor Estuary"),
    ("Widemoor Pool", "V 🐉 Widemoor Pool"),
    ("Widemoor Shore", "V 🐉 Widemoor Shore"),
    ("Willowshade Icemarsh", "V 🐉 Willowshade Icemarsh"),
    ("Willowshade Lake", "V 🐉 Willowshade Lake"),
    ("Willowshade Mire", "V 🐉 Willowshade Mire"),
    ("Willowshade Wetlands", "V 🐉 Willowshade Wetlands"),
    
    # Tier V Forests (🌲)
    ("Brambleshore Hinterlands", "V 🌲 Brambleshore Hinterlands"),
    ("Deadpine Forest", "V 🌲 Deadpine Forest"),
    ("Deepwood Dell", "V 🌲 Deepwood Dell"),
    ("Giantweald Copse", "V 🌲 Giantweald Copse"),
    ("Giantweald Dale", "V 🌲 Giantweald Dale"),
    ("Greenhollow Vale", "V 🌲 Greenhollow Vale"),
    ("Greenshore Peninsula", "V 🌲 Greenshore Peninsula"),
    ("Hightree Dale", "V 🌲 Hightree Dale"),
    ("Hightree Enclave", "V 🌲 Hightree Enclave"),
    ("Hightree Glade", "V 🌲 Hightree Glade"),
    ("Hightree Lake", "V 🌲 Hightree Lake"),
    ("Hightree Steep", "V 🌲 Hightree Steep"),
    ("Hightree Strand", "V 🌲 Hightree Strand"),
    ("Rivercopse Crossing", "V 🌲 Rivercopse Crossing"),
    ("Southgrove Escarp", "V 🌲 Southgrove Escarp"),
    ("Timberscar Dell", "V 🌲 Timberscar Dell"),
    ("Watchwood Grove", "V 🌲 Watchwood Grove"),
    ("Watchwood Precipice", "V 🌲 Watchwood Precipice"),
    ("Westweald Thicket", "V 🌲 Westweald Thicket"),
    ("Windgrass Border", "V 🌲 Windgrass Border"),
    ("Windgrass Gully", "V 🌲 Windgrass Gully"),
    ("Windgrass Precipice", "V 🌲 Windgrass Precipice"),
    ("Windgrass Rill", "V 🌲 Windgrass Rill"),
    
    # Tier V Steppes (🐈)
    ("Avalanche Ravine", "V 🐈 Avalanche Ravine"),
    ("Bleachskull Steppe", "V 🐈 Bleachskull Steppe"),
    ("Braemore Upland", "V 🐈 Braemore Upland"),
    ("Drybasin Riverbed", "V 🐈 Drybasin Riverbed"),
    ("Dryvein Cross", "V 🐈 Dryvein Cross"),
    ("Dryvein Plain", "V 🐈 Dryvein Plain"),
    ("Dryvein Riverbed", "V 🐈 Dryvein Riverbed"),
    ("Flammog Fork", "V 🐈 Flammog Fork"),
    ("Gravemound Brim", "V 🐈 Gravemound Brim"),
    ("Gravemound Hills", "V 🐈 Gravemound Hills"),
    ("Highstone Grassland", "V 🐈 Highstone Grassland"),
    ("Highstone Meadow", "V 🐈 Highstone Meadow"),
    ("Highstone Plains", "V 🐈 Highstone Plains"),
    ("Mudfoot Sump", "V 🐈 Mudfoot Sump"),
    ("Munten Rise", "V 🐈 Munten Rise"),
    ("Murdergulch Cross", "V 🐈 Murdergulch Cross"),
    ("Murdergulch Gap", "V 🐈 Murdergulch Gap"),
    ("Sandmount Esker", "V 🐈 Sandmount Esker"),
    ("Sandmount Strand", "V 🐈 Sandmount Strand"),
    ("Sandrift Coast", "V 🐈 Sandrift Coast"),
    ("Sandrift Prairie", "V 🐈 Sandrift Prairie"),
    ("Sandrift Shore", "V 🐈 Sandrift Shore"),
    ("Sandrift Steppe", "V 🐈 Sandrift Steppe"),
    ("Skysand Plateau", "V 🐈 Skysand Plateau"),
    ("Slakesands Canyon", "V 🐈 Slakesands Canyon"),
    ("Springsump Basin", "V 🐈 Springsump Basin"),
    ("Sunfang Ravine", "V 🐈 Sunfang Ravine"),
    ("Sunstrand Delta", "V 🐈 Sunstrand Delta"),
    ("Sunstrand Shoal", "V 🐈 Sunstrand Shoal"),
    ("Swiftsands Plain", "V 🐈 Swiftsands Plain"),
    ("Thirstwater Steppe", "V 🐈 Thirstwater Steppe"),
    
    # Tier V Highlands (🗻)
    ("Battlebrae Flatland", "V 🗻 Battlebrae Flatland"),
    ("Battlebrae Lake", "V 🗻 Battlebrae Lake"),
    ("Battlebrae Peaks", "V 🗻 Battlebrae Peaks"),
    ("Battlebrae Plain", "V 🗻 Battlebrae Plain"),
    ("Driftwood Vale", "V 🗻 Driftwood Vale"),
    ("Farshore Bay", "V 🗻 Farshore Bay"),
    ("Farshore Esker", "V 🗻 Farshore Esker"),
    ("Flatrock Cliffs", "V 🗻 Flatrock Cliffs"),
    ("Floatshoal Floe", "V 🗻 Floatshoal Floe"),
    ("Meltwater Bog", "V 🗻 Meltwater Bog"),
    ("Northstrand Dunes", "V 🗻 Northstrand Dunes"),
    ("Razorrock Passage", "V 🗻 Razorrock Passage"),
    ("Razorrock Valley", "V 🗻 Razorrock Valley"),
    ("Stonelake Fields", "V 🗻 Stonelake Fields"),
    ("Stonemouth Northbluff", "V 🗻 Stonemouth Northbluff"),
    
    # Tier V Mountains (❄)
    ("Everwinter Crossing", "V ❄ Everwinter Crossing"),
    ("Everwinter Reach", "V ❄ Everwinter Reach"),
    ("Everwinter Shores", "V ❄ Everwinter Shores"),
    ("Frostbite Chasm", "V ❄ Frostbite Chasm"),
    ("Frostpeak Vista", "V ❄ Frostpeak Vista"),
    ("Frostseep Ravine", "V ❄ Frostseep Ravine"),
    ("Glacierfall Passage", "V ❄ Glacierfall Passage"),
    ("Iceburn Firth", "V ❄ Iceburn Firth"),
    ("Whitebank Cross", "V ❄ Whitebank Cross"),
    ("Whitebank Descent", "V ❄ Whitebank Descent"),
    ("Whitebank Shore", "V ❄ Whitebank Shore"),
    ("Whitebank Stream", "V ❄ Whitebank Stream"),
    ("Whitepeak Ascent", "V ❄ Whitepeak Ascent"),
    
    # Tier VI Swamps (🐉)
    ("Drownfield Rut", "VI 🐉 Drownfield Rut"),
    ("Drownfield Slough", "VI 🐉 Drownfield Slough"),
    ("Drownfield Wetland", "VI 🐉 Drownfield Wetland"),
    ("Longfen Arms", "VI 🐉 Longfen Arms"),
    ("Runnelvein Bog", "VI 🐉 Runnelvein Bog"),
    ("Scuttlesink Mouth", "VI 🐉 Scuttlesink Mouth"),
    ("Shaleheath Hills", "VI 🐉 Shaleheath Hills"),
    ("Springsump Wetland", "VI 🐉 Springsump Wetland"),
    ("Widemoor End", "VI 🐉 Widemoor End"),
    ("Widemoor Flats", "VI 🐉 Widemoor Flats"),
    ("Widemoor Hills", "VI 🐉 Widemoor Hills"),
    ("Widemoor Woods", "VI 🐉 Widemoor Woods"),
    ("Willowshade Pools", "VI 🐉 Willowshade Pools"),
    
    # Tier VI Forests (🌲)
    ("Deepwood Gorge", "VI 🌲 Deepwood Gorge"),
    ("Giantweald Roots", "VI 🌲 Giantweald Roots"),
    ("Giantweald Woods", "VI 🌲 Giantweald Woods"),
    ("Hightree Borderlands", "VI 🌲 Hightree Borderlands"),
    ("Hightree Cliffs", "VI 🌲 Hightree Cliffs"),
    ("Hightree Levee", "VI 🌲 Hightree Levee"),
    ("Hightree Pass", "VI 🌲 Hightree Pass"),
    ("Southgrove Copse", "VI 🌲 Southgrove Copse"),
    ("Timberslope Dell", "VI 🌲 Timberslope Dell"),
    ("Timbertop Dale", "VI 🌲 Timbertop Dale"),
    ("Watchwood Bluffs", "VI 🌲 Watchwood Bluffs"),
    ("Watchwood Lakeside", "VI 🌲 Watchwood Lakeside"),
    
    # Tier VI Steppes (🐈)
    ("Bleachskull Desert", "VI 🐈 Bleachskull Desert"),
    ("Drytop Pillars", "VI 🐈 Drytop Pillars"),
    ("Drytop Riverbed", "VI 🐈 Drytop Riverbed"),
    ("Dryvein Oasis", "VI 🐈 Dryvein Oasis"),
    ("Dryvein Steppe", "VI 🐈 Dryvein Steppe"),
    ("Farshore Heath", "VI 🐈 Farshore Heath"),
    ("Firesink Caldera", "VI 🐈 Firesink Caldera"),
    ("Flammog Valley", "VI 🐈 Flammog Valley"),
    ("Mudfoot Mounds", "VI 🐈 Mudfoot Mounds"),
    ("Munten Fell", "VI 🐈 Munten Fell"),
    ("Parchsand Cliffs", "VI 🐈 Parchsand Cliffs"),
    ("Sandrift Expanse", "VI 🐈 Sandrift Expanse"),
    ("Sunfang Approach", "VI 🐈 Sunfang Approach"),
    ("Sunstrand Dunes", "VI 🐈 Sunstrand Dunes"),
    ("Thirstwater Waste", "VI 🐈 Thirstwater Waste"),
    
    # Tier VI Highlands (🗻)
    ("Braemore Lowland", "VI 🗻 Braemore Lowland"),
    ("Driftwood Glen", "VI 🗻 Driftwood Glen"),
    ("Farshore Lagoon", "VI 🗻 Farshore Lagoon"),
    ("Flatrock Plateau", "VI 🗻 Flatrock Plateau"),
    ("Floatshoal Fissure", "VI 🗻 Floatshoal Fissure"),
    ("Gravemound Slope", "VI 🗻 Gravemound Slope"),
    ("Meltwater Delta", "VI 🗻 Meltwater Delta"),
    ("Munten Tundra", "VI 🗻 Munten Tundra"),
    ("Northstrand Beach", "VI 🗻 Northstrand Beach"),
    ("Razorrock Edge", "VI 🗻 Razorrock Edge"),
    ("Razorrock Ravine", "VI 🗻 Razorrock Ravine"),
    ("Skylake Bridge", "VI 🗻 Skylake Bridge"),
    ("Stonelake Hillock", "VI 🗻 Stonelake Hillock"),
    ("Stonemouth Bay", "VI 🗻 Stonemouth Bay"),
    ("Thunderrock Rapids", "VI 🗻 Thunderrock Rapids"),
    ("Windgrass Coast", "VI 🗻 Windgrass Coast"),
    ("Windgrass Fields", "VI 🗻 Windgrass Fields"),
    
    # Tier VI Mountains (❄)
    ("Everwinter Gorge", "VI ❄ Everwinter Gorge"),
    ("Everwinter Peak", "VI ❄ Everwinter Peak"),
    ("Everwinter Plain", "VI ❄ Everwinter Plain"),
    ("Frostbite Mountain", "VI ❄ Frostbite Mountain"),
    ("Frostpeak Ascent", "VI ❄ Frostpeak Ascent"),
    ("Frostspring Passage", "VI ❄ Frostspring Passage"),
    ("Glacierbreak Summit", "VI ❄ Glacierbreak Summit"),
    ("Glacierfall Canyon", "VI ❄ Glacierfall Canyon"),
    ("Iceburn Peaks", "VI ❄ Iceburn Peaks"),
    ("Whitebank Wall", "VI ❄ Whitebank Wall"),
    ("Whitecliff Peak", "VI ❄ Whitecliff Peak"),
    
    # Tier VII Swamps (🐉)
    ("Deathwisp Bog", "VII 🐉 Deathwisp Bog"),
    ("Deathwisp Sink", "VII 🐉 Deathwisp Sink"),
    ("Drownfield Quag", "VII 🐉 Drownfield Quag"),
    ("Longfen Veins", "VII 🐉 Longfen Veins"),
    ("Runnelvein Sink", "VII 🐉 Runnelvein Sink"),
    ("Shaleheath Steep", "VII 🐉 Shaleheath Steep"),
    ("Skullmarsh Upper", "VII 🐉 Skullmarsh Upper"),
    ("Springsump Melt", "VII 🐉 Springsump Melt"),
    ("Twinchannel Narrows", "VII 🐉 Twinchannel Narrows"),
    ("Wetgrave Marsh", "VII 🐉 Wetgrave Marsh"),
    ("Wetgrave Swale", "VII 🐉 Wetgrave Swale"),
    ("Widemoor Fen", "VII 🐉 Widemoor Fen"),
    ("Willowshade Hills", "VII 🐉 Willowshade Hills"),
    ("Willowshade Sink", "VII 🐉 Willowshade Sink"),
    
    # Tier VII Forests (🌲)
    ("Deepwood Copse", "VII 🌲 Deepwood Copse"),
    ("Deepwood Pines", "VII 🌲 Deepwood Pines"),
    ("Giantweald Edge", "VII 🌲 Giantweald Edge"),
    ("Giantweald Glade", "VII 🌲 Giantweald Glade"),
    ("Greenhollow Copse", "VII 🌲 Greenhollow Copse"),
    ("Hightree Hillock", "VII 🌲 Hightree Hillock"),
    ("Hightree Isle", "VII 🌲 Hightree Isle"),
    ("Rivercopse Curve", "VII 🌲 Rivercopse Curve"),
    ("Rivercopse Path", "VII 🌲 Rivercopse Path"),
    ("Southgrove Thicket", "VII 🌲 Southgrove Thicket"),
    ("Sunkenbough Woods", "VII 🌲 Sunkenbough Woods"),
    ("Timberscar Copse", "VII 🌲 Timberscar Copse"),
    ("Timberslope Grove", "VII 🌲 Timberslope Grove"),
    ("Timbertop Wood", "VII 🌲 Timbertop Wood"),
    ("Westweald Shore", "VII 🌲 Westweald Shore"),
    
    # Tier VII Steppes (🐈)
    ("Drybasin Oasis", "VII 🐈 Drybasin Oasis"),
    ("Dryvein Confluence", "VII 🐈 Dryvein Confluence"),
    ("Dryvein End", "VII 🐈 Dryvein End"),
    ("Farshore Drylands", "VII 🐈 Farshore Drylands"),
    ("Firesink Trench", "VII 🐈 Firesink Trench"),
    ("Gravemound Knoll", "VII 🐈 Gravemound Knoll"),
    ("Highstone Mound", "VII 🐈 Highstone Mound"),
    ("Highstone Plateau", "VII 🐈 Highstone Plateau"),
    ("Murdergulch Trail", "VII 🐈 Murdergulch Trail"),
    ("Sandmount Desert", "VII 🐈 Sandmount Desert"),
    ("Sandrift Dunes", "VII 🐈 Sandrift Dunes"),
    ("Sandrift Fringe", "VII 🐈 Sandrift Fringe"),
    ("Skysand Ridge", "VII 🐈 Skysand Ridge"),
    ("Slakesands Mesa", "VII 🐈 Slakesands Mesa"),
    ("Sunfang Cliffs", "VII 🐈 Sunfang Cliffs"),
    ("Sunfang Wasteland", "VII 🐈 Sunfang Wasteland"),
    ("Sunstrand Quicksands", "VII 🐈 Sunstrand Quicksands"),
    ("Swiftsands Basin", "VII 🐈 Swiftsands Basin"),
    ("Thirstwater Gully", "VII 🐈 Thirstwater Gully"),
    
    # Tier VII Highlands (🗻)
    ("Battlebrae Grassland", "VII 🗻 Battlebrae Grassland"),
    ("Battlebrae Meadow", "VII 🗻 Battlebrae Meadow"),
    ("Driftwood Hollow", "VII 🗻 Driftwood Hollow"),
    ("Farshore Cape", "VII 🗻 Farshore Cape"),
    ("Floatshoal Bight", "VII 🗻 Floatshoal Bight"),
    ("Gravemound Cliffs", "VII 🗻 Gravemound Cliffs"),
    ("Meltwater Sump", "VII 🗻 Meltwater Sump"),
    ("Razorrock Bank", "VII 🗻 Razorrock Bank"),
    ("Razorrock Chasm", "VII 🗻 Razorrock Chasm"),
    ("Razorrock Verge", "VII 🗻 Razorrock Verge"),
    ("Skylake Hinterlands", "VII 🗻 Skylake Hinterlands"),
    ("Thunderrock Ascent", "VII 🗻 Thunderrock Ascent"),
    ("Thunderrock Upland", "VII 🗻 Thunderrock Upland"),
    ("Windgrass Terrace", "VII 🗻 Windgrass Terrace"),
    
    # Tier VII Mountains (❄)
    ("Everwinter Expanse", "VII ❄ Everwinter Expanse"),
    ("Everwinter Gap", "VII ❄ Everwinter Gap"),
    ("Everwinter Passage", "VII ❄ Everwinter Passage"),
    ("Frostseep Crevasse", "VII ❄ Frostseep Crevasse"),
    ("Frostspring Volcano", "VII ❄ Frostspring Volcano"),
    ("Glacierfall Cross", "VII ❄ Glacierfall Cross"),
    ("Glacierfall Valley", "VII ❄ Glacierfall Valley"),
    ("Iceburn Cliffs", "VII ❄ Iceburn Cliffs"),
    ("Iceburn Tundra", "VII ❄ Iceburn Tundra"),
    ("Whitebank Ridge", "VII ❄ Whitebank Ridge"),
    ("Whitecliff Expanse", "VII ❄ Whitecliff Expanse"),
    ("Whitepeak Spring", "VII ❄ Whitepeak Spring"),
    ("Whitewall Ridge", "VII ❄ Whitewall Ridge"),
    
    # Tier VIII Swamps (🐉)
    ("Drownfield Sink", "VIII 🐉 Drownfield Sink"),
    ("Meltwater Channel", "VIII 🐉 Meltwater Channel"),
    ("Scuttlesink Marsh", "VIII 🐉 Scuttlesink Marsh"),
    
    # Tier VIII Forests (🌲)
    ("Darkbough Snag", "VIII 🌲 Darkbough Snag"),
    ("Greenshore Bay", "VIII 🌲 Greenshore Bay"),
    ("Redtree Enclave", "VIII 🌲 Redtree Enclave"),
    ("Rivercopse Fount", "VIII 🌲 Rivercopse Fount"),
    ("Sunkenbough Spring", "VIII 🌲 Sunkenbough Spring"),
    ("Timberslope Bridge", "VIII 🌲 Timberslope Bridge"),
    ("Timbertop Escarp", "VIII 🌲 Timbertop Escarp"),
    
    # Tier VIII Steppes (🐈)
    ("Avalanche Incline", "VIII 🐈 Avalanche Incline"),
    ("Flammog Desolation", "VIII 🐈 Flammog Desolation"),
    ("Murdergulch Divide", "VIII 🐈 Murdergulch Divide"),
    ("Murdergulch Ravine", "VIII 🐈 Murdergulch Ravine"),
    ("Parchsand Drought", "VIII 🐈 Parchsand Drought"),
    ("Sandmount Ascent", "VIII 🐈 Sandmount Ascent"),
    ("Sunfang Dawn", "VIII 🐈 Sunfang Dawn"),
    ("Swiftsands Chaparral", "VIII 🐈 Swiftsands Chaparral"),
    
    # Tier VIII Highlands (🗻)
    ("Highstone Loch", "VIII 🗻 Highstone Loch"),
    ("Razorrock Gulch", "VIII 🗻 Razorrock Gulch"),
    ("Stonemouth Southbluff", "VIII 🗻 Stonemouth Southbluff"),
    ("Thunderrock Draw", "VIII 🗻 Thunderrock Draw"),
    
    # Tier VIII Mountains (❄)
    ("Everwinter Incline", "VIII ❄ Everwinter Incline"),
    ("Glacierfall Fissure", "VIII ❄ Glacierfall Fissure"),
    ("Glacierfall Pass", "VIII ❄ Glacierfall Pass"),
    ("Whitepeak Tundra", "VIII ❄ Whitepeak Tundra"),
    ("Whitewall Pass", "VIII ❄ Whitewall Pass"),
    
    # Tier 💀 Swamps (🐉)
    ("Unhallowed Cloister", "💀 🐉 Unhallowed Cloister"),
    ("Black Monastery", "💀 🐉 Black Monastery"),
    ("Deathreach Priory", "💀 🐉 Deathreach Priory"),
    
    # Tier 💀 Forests (🌲)
    ("Eldersleep", "💀 🌲 Eldersleep"),
    ("Eye of the Forest", "💀 🌲 Eye of the Forest"),
    
    # Tier 💀 Steppes (🐈)
    ("Citadel of Ash", "💀 🐈 Citadel of Ash"),
    ("Wailing Bulwark", "💀 🐈 Wailing Bulwark"),
    ("Daemonium Keep", "💀 🐈 Daemonium Keep")
]

